name: Quarto CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your target branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Quarto
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # Step 3: Install dependencies (if needed)
    - name: Install R and dependencies
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'latest'
    - name: Install R packages
      run: |
        Rscript -e 'install.packages("rmarkdown")'
        Rscript -e 'install.packages("reticulate")'
    # Step 4: Render the Quarto document
    - name: Render Quarto Document
      run: quarto render sastopython.qmd # This will render all `.qmd` files in the repository

    # Step 5: Publish to GitHub Pages (optional)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site  # Adjust this if your output directory is different
